reduce allocations
BerserkerDotNet/CaptureRenderTagHelper pull request #1
Opened 2018-03-29 05:16 UTC by jalaz

- Reduce allocations by storing content as `TagHelperContent` on `ScriptBlock` rather than `string` and using methods accepting `IHtmlContent`
- Change behaviour so `render` helper generates one `script` block rather than a collection
- Add benchmarks and unit tests
- Add sample project
- Fix instructions on how to add library

#### Results of benchmarks that compare `Process` method execution on `ScriptRenderTagHelper`
``` ini

BenchmarkDotNet=v0.10.13, OS=ubuntu 17.04
Intel Core i7-7700 CPU 3.60GHz (Kaby Lake), 1 CPU, 8 logical cores and 4 physical cores
.NET Core SDK=2.1.300-preview1-008174
  [Host]     : .NET Core 2.1.0-preview1-26216-03 (CoreCLR 4.6.26216.04, CoreFX 4.6.26216.02), 64bit RyuJIT
  DefaultJob : .NET Core 2.1.0-preview1-26216-03 (CoreCLR 4.6.26216.04, CoreFX 4.6.26216.02), 64bit RyuJIT

```
|     Method | StringLength |      Mean |     Error |    StdDev |    Gen 0 |    Gen 1 |    Gen 2 | Allocated |
|----------- |------------- |----------:|----------:|----------:|---------:|---------:|---------:|----------:|
|    **Process** |         **1000** |  **1.860 us** | **0.0348 us** | **0.0291 us** |   **2.6913** |        **-** |        **-** |  **11.03 KB** |
| NewProcess |         1000 |  1.186 us | 0.0385 us | 0.1059 us |   1.6327 |        - |        - |    6.7 KB |
|    **Process** |        **10000** |  **8.066 us** | **0.1608 us** | **0.3427 us** |  **23.1476** |        **-** |        **-** |     **95 KB** |
| NewProcess |        10000 |  4.646 us | 0.0926 us | 0.1670 us |  13.5117 |   1.9302 |        - |  55.52 KB |
|    **Process** |       **100000** | **98.133 us** | **1.8977 us** | **2.5976 us** | **249.8779** | **249.8779** | **249.8779** | **798.13 KB** |
| NewProcess |       100000 | 52.534 us | 1.0452 us | 1.2036 us | 124.9390 | 124.9390 | 124.9390 | 407.09 KB |

2018-04-19 03:23 UTC, BerserkerDotNet commented on ScriptCaptureTagHelper.UnitTests/RenderShould.cs
> +using Xunit;
Thank you for adding UnitTest to the project, but can you change xUnit to NUnit, please?

2018-04-19 04:00 UTC, BerserkerDotNet requested changes

2018-04-19 04:00 UTC, BerserkerDotNet commented on ScriptCaptureTagHelper/ScriptRenderTagHelper.cs
> +using Microsoft.AspNetCore.Mvc.Razor;
nit: sort

2018-04-19 04:00 UTC, BerserkerDotNet commented on ScriptCaptureTagHelper/ScriptRenderTagHelper.cs
> +                    block.Content.WriteTo(tw, NullHtmlEncoder.Default);
Consider a scenario when the following script blocks are being captured:
```html
<script capture='InlineCapture' src='some good CDN' integrity='sha256-bla' crossorigin='anonymous'></script>
<script capture='InlineCapture'>
 console.log('Foo 2');
</script>
```
If I read your change correctly, it will only render the second one. The first one has no body but has attribuites which are not being rendered. I think the best apparoach is still to render a collection of scripts for now.  I logged an issue #2 to add merging capability.

2018-04-19 04:00 UTC, BerserkerDotNet commented on README.md
> +    @addTagHelper *, ScriptCaptureTagHelper
nice catch :)

2018-04-25 03:33 UTC, jalaz commented
Thanks for your comments. 
I reverted the change that put all captured contents under one `script` tag.
Here are new benchmarks after the change (doesn't contain figures for old implementation since they were presented in the description)

``` ini

BenchmarkDotNet=v0.10.13, OS=ubuntu 17.10
Intel Core i7-7700 CPU 3.60GHz (Kaby Lake), 1 CPU, 8 logical cores and 4 physical cores
.NET Core SDK=2.1.300-preview1-008174
  [Host]     : .NET Core 2.0.6 (CoreCLR 4.6.0.0, CoreFX 4.6.26212.01), 64bit RyuJIT
  DefaultJob : .NET Core 2.0.6 (CoreCLR 4.6.0.0, CoreFX 4.6.26212.01), 64bit RyuJIT


```
|  Method | StringLength |      Mean |     Error |    StdDev |    Gen 0 |    Gen 1 |    Gen 2 | Allocated |
|-------- |------------- |----------:|----------:|----------:|---------:|---------:|---------:|----------:|
| **Process** |         **1000** |  **1.373 us** | **0.0274 us** | **0.0243 us** |   **1.6689** |        **-** |        **-** |   **6.84 KB** |
| **Process** |        **10000** |  **4.420 us** | **0.0882 us** | **0.2369 us** |  **13.5727** |        **-** |        **-** |  **55.66 KB** |
| **Process** |       **100000** | **45.170 us** | **0.8774 us** | **1.1713 us** | **124.9390** | **124.9390** | **124.9390** | **407.22 KB** |

2018-04-26 01:41 UTC, BerserkerDotNet approved these changes

2018-04-26 01:41 UTC, BerserkerDotNet commented on README.md
> +which will expand into a script tag that contains content from two captured tags.
Needs to be reverted as well

2018-04-26 01:41 UTC, BerserkerDotNet commented on README.md
> +which will expand into a script tag that contains content from two captured tags.
Will revert this after merge.

2018-04-26 01:42 UTC, merged