Change name to CaptureRenderTagHelper
BerserkerDotNet/CaptureRenderTagHelper pull request #4
Opened 2019-09-27 08:18 UTC by petero-dk

And update functionality to support the namechange.

2019-09-29 19:23 UTC, BerserkerDotNet requested changes
Overall looks good, I'd like to run a few tests after you fix build issues. (Some references are not resolving)

2019-09-29 19:23 UTC, BerserkerDotNet commented on CaptureRenderTagHelper.Benchmarks/Benchmarks/ScriptCaptureTagBenchmark.cs
> +        private CaptureTagHelper _captureTag;
Rename file to be the same as class name.

2019-09-29 19:23 UTC, BerserkerDotNet commented on CaptureRenderTagHelper.Benchmarks/Benchmarks/ScriptCaptureTagBenchmark.cs
> +        private CaptureTagHelper _captureTag;
Rename file to be the same as class name.
This test is specific to `Capture` functionality, consider naming it `CaptureTagBenchmark`.

2019-09-29 19:23 UTC, BerserkerDotNet commented on CaptureRenderTagHelper.Benchmarks/Benchmarks/ScriptRenderTagBenchmark.cs
>          private TagHelperOutput _renderOutput;
Rename class and file to `RenderTagBenchmark`

2019-09-29 19:23 UTC, BerserkerDotNet commented on CaptureRenderTagHelper.Sample/CaptureRenderTagHelper.Sample.csproj
> -    <Folder Include="Views\Shared" />
Rename

2019-09-29 19:23 UTC, BerserkerDotNet commented on CaptureRenderTagHelper/Extensions/HtmlHelperExtensions.cs
> +            if (htmlHelper.ViewContext.HttpContext.Items.ContainsKey(key) &&
nit: Change to `Element`

2019-09-29 19:23 UTC, BerserkerDotNet commented on CaptureRenderTagHelper/Types/ContentCapture.cs
> +        private readonly List<ContentBlock> _scriptBlocks = new List<ContentBlock>();
nit: _elementBlocks

2019-09-29 19:23 UTC, BerserkerDotNet commented on CaptureRenderTagHelper/CaptureTagHelper.cs
>  {
html element

2019-09-29 19:23 UTC, BerserkerDotNet commented on CaptureRenderTagHelper/CaptureTagHelper.cs
>  {
`html element` here and below

2019-09-29 19:23 UTC, BerserkerDotNet commented on CaptureRenderTagHelper/CaptureTagHelper.cs
> -            capture.Add(content, attributes, order, AllowMerge);
nit: `Element`

2019-09-30 09:02 UTC, petero-dk commented on CaptureRenderTagHelper/CaptureTagHelper.cs
>  {
I think this is fixed now, but I am not sure

2019-09-30 09:02 UTC, petero-dk commented on CaptureRenderTagHelper/CaptureTagHelper.cs
> -            capture.Add(content, attributes, order, AllowMerge);
I think this is fixed now, but I am not sure

2019-10-01 13:27 UTC, petero-dk commented
Did you see the update?

2019-10-08 03:52 UTC, merged

2019-10-08 03:54 UTC, BerserkerDotNet commented
Sorry, I was busy for couple of days. I've merged your PR, I'll need to do some housekeeping around build and add more tests and hopefully, by the end of this week, I'll push a new version to NuGet.

Thank you for the idea and implementation, great work!

2019-10-08 14:38 UTC, petero-dk commented
Perfect, you're welcome. It will be good to be back on the official package again :-)